/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
    status: string;
}
export type FamilyMemberRole = (typeof FamilyMemberRole)[keyof typeof FamilyMemberRole];
export declare const FamilyMemberRole: {
    readonly parent: "parent";
    readonly child: "child";
    readonly grandparent: "grandparent";
    readonly aunt_uncle: "aunt_uncle";
    readonly cousin: "cousin";
    readonly other: "other";
};
export interface FamilyMember {
    id: number;
    userId: string;
    name: string;
    role: FamilyMemberRole;
    color: string;
    avatarInitials: string;
    createdAt: string;
}
export type CreateFamilyMemberBodyRole = (typeof CreateFamilyMemberBodyRole)[keyof typeof CreateFamilyMemberBodyRole];
export declare const CreateFamilyMemberBodyRole: {
    readonly parent: "parent";
    readonly child: "child";
    readonly grandparent: "grandparent";
    readonly aunt_uncle: "aunt_uncle";
    readonly cousin: "cousin";
    readonly other: "other";
};
export interface CreateFamilyMemberBody {
    name: string;
    role: CreateFamilyMemberBodyRole;
    color: string;
    avatarInitials: string;
}
export type CalendarEventCategory = (typeof CalendarEventCategory)[keyof typeof CalendarEventCategory];
export declare const CalendarEventCategory: {
    readonly school: "school";
    readonly work: "work";
    readonly health: "health";
    readonly sports: "sports";
    readonly social: "social";
    readonly family: "family";
    readonly other: "other";
};
export type CalendarEventRecurrence = (typeof CalendarEventRecurrence)[keyof typeof CalendarEventRecurrence];
export declare const CalendarEventRecurrence: {
    readonly none: "none";
    readonly daily: "daily";
    readonly weekly: "weekly";
    readonly biweekly: "biweekly";
    readonly monthly: "monthly";
};
export interface CalendarEvent {
    id: number;
    userId: string;
    title: string;
    description?: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    location?: string;
    familyMemberId?: number;
    color?: string;
    category: CalendarEventCategory;
    recurrence: CalendarEventRecurrence;
    recurrenceDays?: string;
    recurrenceEndDate?: string;
    createdAt: string;
}
export type CreateEventBodyCategory = (typeof CreateEventBodyCategory)[keyof typeof CreateEventBodyCategory];
export declare const CreateEventBodyCategory: {
    readonly school: "school";
    readonly work: "work";
    readonly health: "health";
    readonly sports: "sports";
    readonly social: "social";
    readonly family: "family";
    readonly other: "other";
};
export type CreateEventBodyRecurrence = (typeof CreateEventBodyRecurrence)[keyof typeof CreateEventBodyRecurrence];
export declare const CreateEventBodyRecurrence: {
    readonly none: "none";
    readonly daily: "daily";
    readonly weekly: "weekly";
    readonly biweekly: "biweekly";
    readonly monthly: "monthly";
};
export interface CreateEventBody {
    title: string;
    description?: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    location?: string;
    familyMemberId?: number;
    color?: string;
    category: CreateEventBodyCategory;
    recurrence?: CreateEventBodyRecurrence;
    recurrenceDays?: string;
    recurrenceEndDate?: string;
}
export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority];
export declare const TaskPriority: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
};
export type TaskCategory = (typeof TaskCategory)[keyof typeof TaskCategory];
export declare const TaskCategory: {
    readonly household: "household";
    readonly school: "school";
    readonly errands: "errands";
    readonly health: "health";
    readonly work: "work";
    readonly other: "other";
};
export interface Task {
    id: number;
    userId: string;
    title: string;
    notes?: string;
    completed: boolean;
    dueDate?: string;
    priority: TaskPriority;
    familyMemberId?: number;
    category: TaskCategory;
    createdAt: string;
}
export type CreateTaskBodyPriority = (typeof CreateTaskBodyPriority)[keyof typeof CreateTaskBodyPriority];
export declare const CreateTaskBodyPriority: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
};
export type CreateTaskBodyCategory = (typeof CreateTaskBodyCategory)[keyof typeof CreateTaskBodyCategory];
export declare const CreateTaskBodyCategory: {
    readonly household: "household";
    readonly school: "school";
    readonly errands: "errands";
    readonly health: "health";
    readonly work: "work";
    readonly other: "other";
};
export interface CreateTaskBody {
    title: string;
    notes?: string;
    dueDate?: string;
    priority: CreateTaskBodyPriority;
    familyMemberId?: number;
    category: CreateTaskBodyCategory;
}
export type UpdateTaskBodyPriority = (typeof UpdateTaskBodyPriority)[keyof typeof UpdateTaskBodyPriority];
export declare const UpdateTaskBodyPriority: {
    readonly low: "low";
    readonly medium: "medium";
    readonly high: "high";
};
export type UpdateTaskBodyCategory = (typeof UpdateTaskBodyCategory)[keyof typeof UpdateTaskBodyCategory];
export declare const UpdateTaskBodyCategory: {
    readonly household: "household";
    readonly school: "school";
    readonly errands: "errands";
    readonly health: "health";
    readonly work: "work";
    readonly other: "other";
};
export interface UpdateTaskBody {
    title?: string;
    notes?: string;
    completed?: boolean;
    dueDate?: string;
    priority?: UpdateTaskBodyPriority;
    familyMemberId?: number;
    category?: UpdateTaskBodyCategory;
}
export type MealMealType = (typeof MealMealType)[keyof typeof MealMealType];
export declare const MealMealType: {
    readonly breakfast: "breakfast";
    readonly lunch: "lunch";
    readonly dinner: "dinner";
    readonly snack: "snack";
};
export interface Meal {
    id: number;
    userId: string;
    name: string;
    mealType: MealMealType;
    date: string;
    notes?: string;
    ingredients?: string;
    createdAt: string;
}
export type CreateMealBodyMealType = (typeof CreateMealBodyMealType)[keyof typeof CreateMealBodyMealType];
export declare const CreateMealBodyMealType: {
    readonly breakfast: "breakfast";
    readonly lunch: "lunch";
    readonly dinner: "dinner";
    readonly snack: "snack";
};
export interface CreateMealBody {
    name: string;
    mealType: CreateMealBodyMealType;
    date: string;
    notes?: string;
    ingredients?: string;
}
export interface DashboardSummary {
    totalEvents: number;
    totalTasks: number;
    pendingTasks: number;
    completedTasks: number;
    totalFamilyMembers: number;
    mealsPlannedThisWeek: number;
    eventsToday: number;
    eventsTomorrow: number;
}
export interface Conversation {
    id: number;
    userId: string;
    title: string;
    createdAt: string;
    updatedAt: string;
}
export interface CreateConversationBody {
    title: string;
}
export type MessageRole = (typeof MessageRole)[keyof typeof MessageRole];
export declare const MessageRole: {
    readonly user: "user";
    readonly assistant: "assistant";
};
export interface Message {
    id: number;
    conversationId: number;
    role: MessageRole;
    content: string;
    createdAt: string;
}
export interface SendOpenaiMessageBody {
    content: string;
}
export type ListEventsParams = {
    startDate?: string;
    endDate?: string;
    familyMemberId?: number;
};
export type ListTasksParams = {
    familyMemberId?: number;
    completed?: boolean;
};
export type ListMealsParams = {
    weekOf?: string;
};
//# sourceMappingURL=api.schemas.d.ts.map