/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary List all family members
 */
export declare const ListFamilyMembersResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    name: zod.ZodString;
    role: zod.ZodEnum<["parent", "child", "grandparent", "aunt_uncle", "cousin", "other"]>;
    color: zod.ZodString;
    avatarInitials: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
    createdAt: string;
}, {
    id: number;
    userId: string;
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
    createdAt: string;
}>;
export declare const ListFamilyMembersResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    name: zod.ZodString;
    role: zod.ZodEnum<["parent", "child", "grandparent", "aunt_uncle", "cousin", "other"]>;
    color: zod.ZodString;
    avatarInitials: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
    createdAt: string;
}, {
    id: number;
    userId: string;
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
    createdAt: string;
}>, "many">;
/**
 * @summary Create a family member
 */
export declare const CreateFamilyMemberBody: zod.ZodObject<{
    name: zod.ZodString;
    role: zod.ZodEnum<["parent", "child", "grandparent", "aunt_uncle", "cousin", "other"]>;
    color: zod.ZodString;
    avatarInitials: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
}, {
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
}>;
export declare const GetFamilyMemberParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetFamilyMemberResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    name: zod.ZodString;
    role: zod.ZodEnum<["parent", "child", "grandparent", "aunt_uncle", "cousin", "other"]>;
    color: zod.ZodString;
    avatarInitials: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
    createdAt: string;
}, {
    id: number;
    userId: string;
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
    createdAt: string;
}>;
export declare const UpdateFamilyMemberParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateFamilyMemberBody: zod.ZodObject<{
    name: zod.ZodString;
    role: zod.ZodEnum<["parent", "child", "grandparent", "aunt_uncle", "cousin", "other"]>;
    color: zod.ZodString;
    avatarInitials: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
}, {
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
}>;
export declare const UpdateFamilyMemberResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    name: zod.ZodString;
    role: zod.ZodEnum<["parent", "child", "grandparent", "aunt_uncle", "cousin", "other"]>;
    color: zod.ZodString;
    avatarInitials: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
    createdAt: string;
}, {
    id: number;
    userId: string;
    name: string;
    role: "parent" | "child" | "grandparent" | "aunt_uncle" | "cousin" | "other";
    color: string;
    avatarInitials: string;
    createdAt: string;
}>;
export declare const DeleteFamilyMemberParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List calendar events
 */
export declare const ListEventsQueryParams: zod.ZodObject<{
    startDate: zod.ZodOptional<zod.ZodString>;
    endDate: zod.ZodOptional<zod.ZodString>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
}, "strip", zod.ZodTypeAny, {
    startDate?: string | undefined;
    endDate?: string | undefined;
    familyMemberId?: number | undefined;
}, {
    startDate?: string | undefined;
    endDate?: string | undefined;
    familyMemberId?: number | undefined;
}>;
export declare const ListEventsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    startTime: zod.ZodString;
    endTime: zod.ZodString;
    allDay: zod.ZodBoolean;
    location: zod.ZodOptional<zod.ZodString>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    color: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodEnum<["school", "work", "health", "sports", "social", "family", "other"]>;
    recurrence: zod.ZodEnum<["none", "daily", "weekly", "biweekly", "monthly"]>;
    recurrenceDays: zod.ZodOptional<zod.ZodString>;
    recurrenceEndDate: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}>;
export declare const ListEventsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    startTime: zod.ZodString;
    endTime: zod.ZodString;
    allDay: zod.ZodBoolean;
    location: zod.ZodOptional<zod.ZodString>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    color: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodEnum<["school", "work", "health", "sports", "social", "family", "other"]>;
    recurrence: zod.ZodEnum<["none", "daily", "weekly", "biweekly", "monthly"]>;
    recurrenceDays: zod.ZodOptional<zod.ZodString>;
    recurrenceEndDate: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}>, "many">;
/**
 * @summary Create a calendar event
 */
export declare const CreateEventBody: zod.ZodObject<{
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    startTime: zod.ZodString;
    endTime: zod.ZodString;
    allDay: zod.ZodBoolean;
    location: zod.ZodOptional<zod.ZodString>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    color: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodEnum<["school", "work", "health", "sports", "social", "family", "other"]>;
    recurrence: zod.ZodOptional<zod.ZodEnum<["none", "daily", "weekly", "biweekly", "monthly"]>>;
    recurrenceDays: zod.ZodOptional<zod.ZodString>;
    recurrenceEndDate: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrence?: "none" | "daily" | "weekly" | "biweekly" | "monthly" | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}, {
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrence?: "none" | "daily" | "weekly" | "biweekly" | "monthly" | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}>;
export declare const GetEventParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetEventResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    startTime: zod.ZodString;
    endTime: zod.ZodString;
    allDay: zod.ZodBoolean;
    location: zod.ZodOptional<zod.ZodString>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    color: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodEnum<["school", "work", "health", "sports", "social", "family", "other"]>;
    recurrence: zod.ZodEnum<["none", "daily", "weekly", "biweekly", "monthly"]>;
    recurrenceDays: zod.ZodOptional<zod.ZodString>;
    recurrenceEndDate: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}>;
export declare const UpdateEventParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateEventBody: zod.ZodObject<{
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    startTime: zod.ZodString;
    endTime: zod.ZodString;
    allDay: zod.ZodBoolean;
    location: zod.ZodOptional<zod.ZodString>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    color: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodEnum<["school", "work", "health", "sports", "social", "family", "other"]>;
    recurrence: zod.ZodOptional<zod.ZodEnum<["none", "daily", "weekly", "biweekly", "monthly"]>>;
    recurrenceDays: zod.ZodOptional<zod.ZodString>;
    recurrenceEndDate: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrence?: "none" | "daily" | "weekly" | "biweekly" | "monthly" | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}, {
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrence?: "none" | "daily" | "weekly" | "biweekly" | "monthly" | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}>;
export declare const UpdateEventResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    startTime: zod.ZodString;
    endTime: zod.ZodString;
    allDay: zod.ZodBoolean;
    location: zod.ZodOptional<zod.ZodString>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    color: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodEnum<["school", "work", "health", "sports", "social", "family", "other"]>;
    recurrence: zod.ZodEnum<["none", "daily", "weekly", "biweekly", "monthly"]>;
    recurrenceDays: zod.ZodOptional<zod.ZodString>;
    recurrenceEndDate: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}>;
export declare const DeleteEventParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List tasks
 */
export declare const ListTasksQueryParams: zod.ZodObject<{
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    completed: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    familyMemberId?: number | undefined;
    completed?: boolean | undefined;
}, {
    familyMemberId?: number | undefined;
    completed?: boolean | undefined;
}>;
export declare const ListTasksResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    completed: zod.ZodBoolean;
    dueDate: zod.ZodOptional<zod.ZodString>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    category: zod.ZodEnum<["household", "school", "errands", "health", "work", "other"]>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    completed: boolean;
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    completed: boolean;
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}>;
export declare const ListTasksResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    completed: zod.ZodBoolean;
    dueDate: zod.ZodOptional<zod.ZodString>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    category: zod.ZodEnum<["household", "school", "errands", "health", "work", "other"]>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    completed: boolean;
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    completed: boolean;
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}>, "many">;
/**
 * @summary Create a task
 */
export declare const CreateTaskBody: zod.ZodObject<{
    title: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    dueDate: zod.ZodOptional<zod.ZodString>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    category: zod.ZodEnum<["household", "school", "errands", "health", "work", "other"]>;
}, "strip", zod.ZodTypeAny, {
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}, {
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}>;
export declare const UpdateTaskParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateTaskBody: zod.ZodObject<{
    title: zod.ZodOptional<zod.ZodString>;
    notes: zod.ZodOptional<zod.ZodString>;
    completed: zod.ZodOptional<zod.ZodBoolean>;
    dueDate: zod.ZodOptional<zod.ZodString>;
    priority: zod.ZodOptional<zod.ZodEnum<["low", "medium", "high"]>>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    category: zod.ZodOptional<zod.ZodEnum<["household", "school", "errands", "health", "work", "other"]>>;
}, "strip", zod.ZodTypeAny, {
    familyMemberId?: number | undefined;
    title?: string | undefined;
    category?: "other" | "school" | "work" | "health" | "household" | "errands" | undefined;
    completed?: boolean | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
    priority?: "low" | "medium" | "high" | undefined;
}, {
    familyMemberId?: number | undefined;
    title?: string | undefined;
    category?: "other" | "school" | "work" | "health" | "household" | "errands" | undefined;
    completed?: boolean | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
    priority?: "low" | "medium" | "high" | undefined;
}>;
export declare const UpdateTaskResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    completed: zod.ZodBoolean;
    dueDate: zod.ZodOptional<zod.ZodString>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    category: zod.ZodEnum<["household", "school", "errands", "health", "work", "other"]>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    completed: boolean;
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    completed: boolean;
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}>;
export declare const DeleteTaskParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary List meal plans
 */
export declare const ListMealsQueryParams: zod.ZodObject<{
    weekOf: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    weekOf?: string | undefined;
}, {
    weekOf?: string | undefined;
}>;
export declare const ListMealsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    name: zod.ZodString;
    mealType: zod.ZodEnum<["breakfast", "lunch", "dinner", "snack"]>;
    date: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    ingredients: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    name: string;
    date: string;
    createdAt: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}, {
    id: number;
    userId: string;
    name: string;
    date: string;
    createdAt: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}>;
export declare const ListMealsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    name: zod.ZodString;
    mealType: zod.ZodEnum<["breakfast", "lunch", "dinner", "snack"]>;
    date: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    ingredients: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    name: string;
    date: string;
    createdAt: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}, {
    id: number;
    userId: string;
    name: string;
    date: string;
    createdAt: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}>, "many">;
/**
 * @summary Create a meal plan entry
 */
export declare const CreateMealBody: zod.ZodObject<{
    name: zod.ZodString;
    mealType: zod.ZodEnum<["breakfast", "lunch", "dinner", "snack"]>;
    date: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    ingredients: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    date: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}, {
    name: string;
    date: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}>;
export declare const UpdateMealParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateMealBody: zod.ZodObject<{
    name: zod.ZodString;
    mealType: zod.ZodEnum<["breakfast", "lunch", "dinner", "snack"]>;
    date: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    ingredients: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    date: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}, {
    name: string;
    date: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}>;
export declare const UpdateMealResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    name: zod.ZodString;
    mealType: zod.ZodEnum<["breakfast", "lunch", "dinner", "snack"]>;
    date: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    ingredients: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    name: string;
    date: string;
    createdAt: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}, {
    id: number;
    userId: string;
    name: string;
    date: string;
    createdAt: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}>;
export declare const DeleteMealParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
/**
 * @summary Get dashboard summary counts and upcoming items
 */
export declare const GetDashboardSummaryResponse: zod.ZodObject<{
    totalEvents: zod.ZodNumber;
    totalTasks: zod.ZodNumber;
    pendingTasks: zod.ZodNumber;
    completedTasks: zod.ZodNumber;
    totalFamilyMembers: zod.ZodNumber;
    mealsPlannedThisWeek: zod.ZodNumber;
    eventsToday: zod.ZodNumber;
    eventsTomorrow: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    totalEvents: number;
    totalTasks: number;
    pendingTasks: number;
    completedTasks: number;
    totalFamilyMembers: number;
    mealsPlannedThisWeek: number;
    eventsToday: number;
    eventsTomorrow: number;
}, {
    totalEvents: number;
    totalTasks: number;
    pendingTasks: number;
    completedTasks: number;
    totalFamilyMembers: number;
    mealsPlannedThisWeek: number;
    eventsToday: number;
    eventsTomorrow: number;
}>;
/**
 * @summary Get next 7 days of events
 */
export declare const GetUpcomingEventsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    startTime: zod.ZodString;
    endTime: zod.ZodString;
    allDay: zod.ZodBoolean;
    location: zod.ZodOptional<zod.ZodString>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    color: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodEnum<["school", "work", "health", "sports", "social", "family", "other"]>;
    recurrence: zod.ZodEnum<["none", "daily", "weekly", "biweekly", "monthly"]>;
    recurrenceDays: zod.ZodOptional<zod.ZodString>;
    recurrenceEndDate: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}>;
export declare const GetUpcomingEventsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    description: zod.ZodOptional<zod.ZodString>;
    startTime: zod.ZodString;
    endTime: zod.ZodString;
    allDay: zod.ZodBoolean;
    location: zod.ZodOptional<zod.ZodString>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    color: zod.ZodOptional<zod.ZodString>;
    category: zod.ZodEnum<["school", "work", "health", "sports", "social", "family", "other"]>;
    recurrence: zod.ZodEnum<["none", "daily", "weekly", "biweekly", "monthly"]>;
    recurrenceDays: zod.ZodOptional<zod.ZodString>;
    recurrenceEndDate: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    startTime: string;
    endTime: string;
    allDay: boolean;
    category: "other" | "school" | "work" | "health" | "sports" | "social" | "family";
    recurrence: "none" | "daily" | "weekly" | "biweekly" | "monthly";
    color?: string | undefined;
    familyMemberId?: number | undefined;
    description?: string | undefined;
    location?: string | undefined;
    recurrenceDays?: string | undefined;
    recurrenceEndDate?: string | undefined;
}>, "many">;
/**
 * @summary Get all incomplete tasks
 */
export declare const GetPendingTasksResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    completed: zod.ZodBoolean;
    dueDate: zod.ZodOptional<zod.ZodString>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    category: zod.ZodEnum<["household", "school", "errands", "health", "work", "other"]>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    completed: boolean;
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    completed: boolean;
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}>;
export declare const GetPendingTasksResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    completed: zod.ZodBoolean;
    dueDate: zod.ZodOptional<zod.ZodString>;
    priority: zod.ZodEnum<["low", "medium", "high"]>;
    familyMemberId: zod.ZodOptional<zod.ZodNumber>;
    category: zod.ZodEnum<["household", "school", "errands", "health", "work", "other"]>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    completed: boolean;
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    category: "other" | "school" | "work" | "health" | "household" | "errands";
    completed: boolean;
    priority: "low" | "medium" | "high";
    familyMemberId?: number | undefined;
    notes?: string | undefined;
    dueDate?: string | undefined;
}>, "many">;
/**
 * @summary Get this week's meal plan
 */
export declare const GetThisWeekMealsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    name: zod.ZodString;
    mealType: zod.ZodEnum<["breakfast", "lunch", "dinner", "snack"]>;
    date: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    ingredients: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    name: string;
    date: string;
    createdAt: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}, {
    id: number;
    userId: string;
    name: string;
    date: string;
    createdAt: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}>;
export declare const GetThisWeekMealsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    name: zod.ZodString;
    mealType: zod.ZodEnum<["breakfast", "lunch", "dinner", "snack"]>;
    date: zod.ZodString;
    notes: zod.ZodOptional<zod.ZodString>;
    ingredients: zod.ZodOptional<zod.ZodString>;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    name: string;
    date: string;
    createdAt: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}, {
    id: number;
    userId: string;
    name: string;
    date: string;
    createdAt: string;
    mealType: "breakfast" | "lunch" | "dinner" | "snack";
    notes?: string | undefined;
    ingredients?: string | undefined;
}>, "many">;
/**
 * @summary List AI conversations
 */
export declare const ListOpenaiConversationsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    updatedAt: string;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    updatedAt: string;
}>;
export declare const ListOpenaiConversationsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    userId: zod.ZodString;
    title: zod.ZodString;
    createdAt: zod.ZodString;
    updatedAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    updatedAt: string;
}, {
    id: number;
    userId: string;
    createdAt: string;
    title: string;
    updatedAt: string;
}>, "many">;
/**
 * @summary Create a new AI conversation
 */
export declare const CreateOpenaiConversationBody: zod.ZodObject<{
    title: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    title: string;
}, {
    title: string;
}>;
export declare const ListOpenaiConversationMessagesParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const ListOpenaiConversationMessagesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    conversationId: zod.ZodNumber;
    role: zod.ZodEnum<["user", "assistant"]>;
    content: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    role: "user" | "assistant";
    createdAt: string;
    conversationId: number;
    content: string;
}, {
    id: number;
    role: "user" | "assistant";
    createdAt: string;
    conversationId: number;
    content: string;
}>;
export declare const ListOpenaiConversationMessagesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    conversationId: zod.ZodNumber;
    role: zod.ZodEnum<["user", "assistant"]>;
    content: zod.ZodString;
    createdAt: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    id: number;
    role: "user" | "assistant";
    createdAt: string;
    conversationId: number;
    content: string;
}, {
    id: number;
    role: "user" | "assistant";
    createdAt: string;
    conversationId: number;
    content: string;
}>, "many">;
export declare const SendOpenaiMessageParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const SendOpenaiMessageBody: zod.ZodObject<{
    content: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    content: string;
}, {
    content: string;
}>;
//# sourceMappingURL=api.d.ts.map