/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type FamilyMemberRole =
  (typeof FamilyMemberRole)[keyof typeof FamilyMemberRole];

export const FamilyMemberRole = {
  parent: "parent",
  child: "child",
  grandparent: "grandparent",
  aunt_uncle: "aunt_uncle",
  cousin: "cousin",
  other: "other",
} as const;

export interface FamilyMember {
  id: number;
  userId: string;
  name: string;
  role: FamilyMemberRole;
  color: string;
  avatarInitials: string;
  createdAt: string;
}

export type CreateFamilyMemberBodyRole =
  (typeof CreateFamilyMemberBodyRole)[keyof typeof CreateFamilyMemberBodyRole];

export const CreateFamilyMemberBodyRole = {
  parent: "parent",
  child: "child",
  grandparent: "grandparent",
  aunt_uncle: "aunt_uncle",
  cousin: "cousin",
  other: "other",
} as const;

export interface CreateFamilyMemberBody {
  name: string;
  role: CreateFamilyMemberBodyRole;
  color: string;
  avatarInitials: string;
}

export type CalendarEventCategory =
  (typeof CalendarEventCategory)[keyof typeof CalendarEventCategory];

export const CalendarEventCategory = {
  school: "school",
  work: "work",
  health: "health",
  sports: "sports",
  social: "social",
  family: "family",
  other: "other",
} as const;

export type CalendarEventRecurrence =
  (typeof CalendarEventRecurrence)[keyof typeof CalendarEventRecurrence];

export const CalendarEventRecurrence = {
  none: "none",
  daily: "daily",
  weekly: "weekly",
  biweekly: "biweekly",
  monthly: "monthly",
} as const;

export interface CalendarEvent {
  id: number;
  userId: string;
  title: string;
  description?: string;
  startTime: string;
  endTime: string;
  allDay: boolean;
  location?: string;
  familyMemberId?: number;
  color?: string;
  category: CalendarEventCategory;
  recurrence: CalendarEventRecurrence;
  recurrenceDays?: string;
  recurrenceEndDate?: string;
  createdAt: string;
}

export type CreateEventBodyCategory =
  (typeof CreateEventBodyCategory)[keyof typeof CreateEventBodyCategory];

export const CreateEventBodyCategory = {
  school: "school",
  work: "work",
  health: "health",
  sports: "sports",
  social: "social",
  family: "family",
  other: "other",
} as const;

export type CreateEventBodyRecurrence =
  (typeof CreateEventBodyRecurrence)[keyof typeof CreateEventBodyRecurrence];

export const CreateEventBodyRecurrence = {
  none: "none",
  daily: "daily",
  weekly: "weekly",
  biweekly: "biweekly",
  monthly: "monthly",
} as const;

export interface CreateEventBody {
  title: string;
  description?: string;
  startTime: string;
  endTime: string;
  allDay: boolean;
  location?: string;
  familyMemberId?: number;
  color?: string;
  category: CreateEventBodyCategory;
  recurrence?: CreateEventBodyRecurrence;
  recurrenceDays?: string;
  recurrenceEndDate?: string;
}

export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority];

export const TaskPriority = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export type TaskCategory = (typeof TaskCategory)[keyof typeof TaskCategory];

export const TaskCategory = {
  household: "household",
  school: "school",
  errands: "errands",
  health: "health",
  work: "work",
  other: "other",
} as const;

export interface Task {
  id: number;
  userId: string;
  title: string;
  notes?: string;
  completed: boolean;
  dueDate?: string;
  priority: TaskPriority;
  familyMemberId?: number;
  category: TaskCategory;
  createdAt: string;
}

export type CreateTaskBodyPriority =
  (typeof CreateTaskBodyPriority)[keyof typeof CreateTaskBodyPriority];

export const CreateTaskBodyPriority = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export type CreateTaskBodyCategory =
  (typeof CreateTaskBodyCategory)[keyof typeof CreateTaskBodyCategory];

export const CreateTaskBodyCategory = {
  household: "household",
  school: "school",
  errands: "errands",
  health: "health",
  work: "work",
  other: "other",
} as const;

export interface CreateTaskBody {
  title: string;
  notes?: string;
  dueDate?: string;
  priority: CreateTaskBodyPriority;
  familyMemberId?: number;
  category: CreateTaskBodyCategory;
}

export type UpdateTaskBodyPriority =
  (typeof UpdateTaskBodyPriority)[keyof typeof UpdateTaskBodyPriority];

export const UpdateTaskBodyPriority = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export type UpdateTaskBodyCategory =
  (typeof UpdateTaskBodyCategory)[keyof typeof UpdateTaskBodyCategory];

export const UpdateTaskBodyCategory = {
  household: "household",
  school: "school",
  errands: "errands",
  health: "health",
  work: "work",
  other: "other",
} as const;

export interface UpdateTaskBody {
  title?: string;
  notes?: string;
  completed?: boolean;
  dueDate?: string;
  priority?: UpdateTaskBodyPriority;
  familyMemberId?: number;
  category?: UpdateTaskBodyCategory;
}

export type MealMealType = (typeof MealMealType)[keyof typeof MealMealType];

export const MealMealType = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
} as const;

export interface Meal {
  id: number;
  userId: string;
  name: string;
  mealType: MealMealType;
  date: string;
  notes?: string;
  ingredients?: string;
  createdAt: string;
}

export type CreateMealBodyMealType =
  (typeof CreateMealBodyMealType)[keyof typeof CreateMealBodyMealType];

export const CreateMealBodyMealType = {
  breakfast: "breakfast",
  lunch: "lunch",
  dinner: "dinner",
  snack: "snack",
} as const;

export interface CreateMealBody {
  name: string;
  mealType: CreateMealBodyMealType;
  date: string;
  notes?: string;
  ingredients?: string;
}

export interface DashboardSummary {
  totalEvents: number;
  totalTasks: number;
  pendingTasks: number;
  completedTasks: number;
  totalFamilyMembers: number;
  mealsPlannedThisWeek: number;
  eventsToday: number;
  eventsTomorrow: number;
}

export interface Conversation {
  id: number;
  userId: string;
  title: string;
  createdAt: string;
  updatedAt: string;
}

export interface CreateConversationBody {
  title: string;
}

export type MessageRole = (typeof MessageRole)[keyof typeof MessageRole];

export const MessageRole = {
  user: "user",
  assistant: "assistant",
} as const;

export interface Message {
  id: number;
  conversationId: number;
  role: MessageRole;
  content: string;
  createdAt: string;
}

export interface SendOpenaiMessageBody {
  content: string;
}

export type ListEventsParams = {
  startDate?: string;
  endDate?: string;
  familyMemberId?: number;
};

export type ListTasksParams = {
  familyMemberId?: number;
  completed?: boolean;
};

export type ListMealsParams = {
  weekOf?: string;
};
