/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CalendarEvent,
  Conversation,
  CreateConversationBody,
  CreateEventBody,
  CreateFamilyMemberBody,
  CreateMealBody,
  CreateTaskBody,
  DashboardSummary,
  FamilyMember,
  HealthStatus,
  ListEventsParams,
  ListMealsParams,
  ListTasksParams,
  Meal,
  Message,
  SendOpenaiMessageBody,
  Task,
  UpdateTaskBody,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all family members
 */
export const getListFamilyMembersUrl = () => {
  return `/api/family-members`;
};

export const listFamilyMembers = async (
  options?: RequestInit,
): Promise<FamilyMember[]> => {
  return customFetch<FamilyMember[]>(getListFamilyMembersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListFamilyMembersQueryKey = () => {
  return [`/api/family-members`] as const;
};

export const getListFamilyMembersQueryOptions = <
  TData = Awaited<ReturnType<typeof listFamilyMembers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listFamilyMembers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListFamilyMembersQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listFamilyMembers>>
  > = ({ signal }) => listFamilyMembers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listFamilyMembers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListFamilyMembersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listFamilyMembers>>
>;
export type ListFamilyMembersQueryError = ErrorType<unknown>;

/**
 * @summary List all family members
 */

export function useListFamilyMembers<
  TData = Awaited<ReturnType<typeof listFamilyMembers>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listFamilyMembers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListFamilyMembersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a family member
 */
export const getCreateFamilyMemberUrl = () => {
  return `/api/family-members`;
};

export const createFamilyMember = async (
  createFamilyMemberBody: CreateFamilyMemberBody,
  options?: RequestInit,
): Promise<FamilyMember> => {
  return customFetch<FamilyMember>(getCreateFamilyMemberUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createFamilyMemberBody),
  });
};

export const getCreateFamilyMemberMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createFamilyMember>>,
    TError,
    { data: BodyType<CreateFamilyMemberBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createFamilyMember>>,
  TError,
  { data: BodyType<CreateFamilyMemberBody> },
  TContext
> => {
  const mutationKey = ["createFamilyMember"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createFamilyMember>>,
    { data: BodyType<CreateFamilyMemberBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createFamilyMember(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateFamilyMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof createFamilyMember>>
>;
export type CreateFamilyMemberMutationBody = BodyType<CreateFamilyMemberBody>;
export type CreateFamilyMemberMutationError = ErrorType<unknown>;

/**
 * @summary Create a family member
 */
export const useCreateFamilyMember = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createFamilyMember>>,
    TError,
    { data: BodyType<CreateFamilyMemberBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createFamilyMember>>,
  TError,
  { data: BodyType<CreateFamilyMemberBody> },
  TContext
> => {
  return useMutation(getCreateFamilyMemberMutationOptions(options));
};

export const getGetFamilyMemberUrl = (id: number) => {
  return `/api/family-members/${id}`;
};

export const getFamilyMember = async (
  id: number,
  options?: RequestInit,
): Promise<FamilyMember> => {
  return customFetch<FamilyMember>(getGetFamilyMemberUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetFamilyMemberQueryKey = (id: number) => {
  return [`/api/family-members/${id}`] as const;
};

export const getGetFamilyMemberQueryOptions = <
  TData = Awaited<ReturnType<typeof getFamilyMember>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getFamilyMember>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFamilyMemberQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFamilyMember>>> = ({
    signal,
  }) => getFamilyMember(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getFamilyMember>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetFamilyMemberQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFamilyMember>>
>;
export type GetFamilyMemberQueryError = ErrorType<unknown>;

export function useGetFamilyMember<
  TData = Awaited<ReturnType<typeof getFamilyMember>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getFamilyMember>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetFamilyMemberQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getUpdateFamilyMemberUrl = (id: number) => {
  return `/api/family-members/${id}`;
};

export const updateFamilyMember = async (
  id: number,
  createFamilyMemberBody: CreateFamilyMemberBody,
  options?: RequestInit,
): Promise<FamilyMember> => {
  return customFetch<FamilyMember>(getUpdateFamilyMemberUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createFamilyMemberBody),
  });
};

export const getUpdateFamilyMemberMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateFamilyMember>>,
    TError,
    { id: number; data: BodyType<CreateFamilyMemberBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateFamilyMember>>,
  TError,
  { id: number; data: BodyType<CreateFamilyMemberBody> },
  TContext
> => {
  const mutationKey = ["updateFamilyMember"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateFamilyMember>>,
    { id: number; data: BodyType<CreateFamilyMemberBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateFamilyMember(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateFamilyMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateFamilyMember>>
>;
export type UpdateFamilyMemberMutationBody = BodyType<CreateFamilyMemberBody>;
export type UpdateFamilyMemberMutationError = ErrorType<unknown>;

export const useUpdateFamilyMember = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateFamilyMember>>,
    TError,
    { id: number; data: BodyType<CreateFamilyMemberBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateFamilyMember>>,
  TError,
  { id: number; data: BodyType<CreateFamilyMemberBody> },
  TContext
> => {
  return useMutation(getUpdateFamilyMemberMutationOptions(options));
};

export const getDeleteFamilyMemberUrl = (id: number) => {
  return `/api/family-members/${id}`;
};

export const deleteFamilyMember = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteFamilyMemberUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteFamilyMemberMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteFamilyMember>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteFamilyMember>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteFamilyMember"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteFamilyMember>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteFamilyMember(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteFamilyMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteFamilyMember>>
>;

export type DeleteFamilyMemberMutationError = ErrorType<unknown>;

export const useDeleteFamilyMember = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteFamilyMember>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteFamilyMember>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteFamilyMemberMutationOptions(options));
};

/**
 * @summary List calendar events
 */
export const getListEventsUrl = (params?: ListEventsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/events?${stringifiedParams}`
    : `/api/events`;
};

export const listEvents = async (
  params?: ListEventsParams,
  options?: RequestInit,
): Promise<CalendarEvent[]> => {
  return customFetch<CalendarEvent[]>(getListEventsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListEventsQueryKey = (params?: ListEventsParams) => {
  return [`/api/events`, ...(params ? [params] : [])] as const;
};

export const getListEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof listEvents>>,
  TError = ErrorType<unknown>,
>(
  params?: ListEventsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listEvents>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListEventsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listEvents>>> = ({
    signal,
  }) => listEvents(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listEvents>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listEvents>>
>;
export type ListEventsQueryError = ErrorType<unknown>;

/**
 * @summary List calendar events
 */

export function useListEvents<
  TData = Awaited<ReturnType<typeof listEvents>>,
  TError = ErrorType<unknown>,
>(
  params?: ListEventsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listEvents>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListEventsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a calendar event
 */
export const getCreateEventUrl = () => {
  return `/api/events`;
};

export const createEvent = async (
  createEventBody: CreateEventBody,
  options?: RequestInit,
): Promise<CalendarEvent> => {
  return customFetch<CalendarEvent>(getCreateEventUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createEventBody),
  });
};

export const getCreateEventMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createEvent>>,
    TError,
    { data: BodyType<CreateEventBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createEvent>>,
  TError,
  { data: BodyType<CreateEventBody> },
  TContext
> => {
  const mutationKey = ["createEvent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createEvent>>,
    { data: BodyType<CreateEventBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createEvent(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof createEvent>>
>;
export type CreateEventMutationBody = BodyType<CreateEventBody>;
export type CreateEventMutationError = ErrorType<unknown>;

/**
 * @summary Create a calendar event
 */
export const useCreateEvent = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createEvent>>,
    TError,
    { data: BodyType<CreateEventBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createEvent>>,
  TError,
  { data: BodyType<CreateEventBody> },
  TContext
> => {
  return useMutation(getCreateEventMutationOptions(options));
};

export const getGetEventUrl = (id: number) => {
  return `/api/events/${id}`;
};

export const getEvent = async (
  id: number,
  options?: RequestInit,
): Promise<CalendarEvent> => {
  return customFetch<CalendarEvent>(getGetEventUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getGetEventQueryKey = (id: number) => {
  return [`/api/events/${id}`] as const;
};

export const getGetEventQueryOptions = <
  TData = Awaited<ReturnType<typeof getEvent>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getEvent>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetEventQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getEvent>>> = ({
    signal,
  }) => getEvent(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getEvent>>, TError, TData> & {
    queryKey: QueryKey;
  };
};

export type GetEventQueryResult = NonNullable<
  Awaited<ReturnType<typeof getEvent>>
>;
export type GetEventQueryError = ErrorType<unknown>;

export function useGetEvent<
  TData = Awaited<ReturnType<typeof getEvent>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getEvent>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetEventQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getUpdateEventUrl = (id: number) => {
  return `/api/events/${id}`;
};

export const updateEvent = async (
  id: number,
  createEventBody: CreateEventBody,
  options?: RequestInit,
): Promise<CalendarEvent> => {
  return customFetch<CalendarEvent>(getUpdateEventUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createEventBody),
  });
};

export const getUpdateEventMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateEvent>>,
    TError,
    { id: number; data: BodyType<CreateEventBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateEvent>>,
  TError,
  { id: number; data: BodyType<CreateEventBody> },
  TContext
> => {
  const mutationKey = ["updateEvent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateEvent>>,
    { id: number; data: BodyType<CreateEventBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateEvent(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateEvent>>
>;
export type UpdateEventMutationBody = BodyType<CreateEventBody>;
export type UpdateEventMutationError = ErrorType<unknown>;

export const useUpdateEvent = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateEvent>>,
    TError,
    { id: number; data: BodyType<CreateEventBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateEvent>>,
  TError,
  { id: number; data: BodyType<CreateEventBody> },
  TContext
> => {
  return useMutation(getUpdateEventMutationOptions(options));
};

export const getDeleteEventUrl = (id: number) => {
  return `/api/events/${id}`;
};

export const deleteEvent = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteEventUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteEventMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteEvent>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteEvent>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteEvent"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteEvent>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteEvent(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteEventMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteEvent>>
>;

export type DeleteEventMutationError = ErrorType<unknown>;

export const useDeleteEvent = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteEvent>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteEvent>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteEventMutationOptions(options));
};

/**
 * @summary List tasks
 */
export const getListTasksUrl = (params?: ListTasksParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/tasks?${stringifiedParams}`
    : `/api/tasks`;
};

export const listTasks = async (
  params?: ListTasksParams,
  options?: RequestInit,
): Promise<Task[]> => {
  return customFetch<Task[]>(getListTasksUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListTasksQueryKey = (params?: ListTasksParams) => {
  return [`/api/tasks`, ...(params ? [params] : [])] as const;
};

export const getListTasksQueryOptions = <
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = ErrorType<unknown>,
>(
  params?: ListTasksParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listTasks>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTasksQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTasks>>> = ({
    signal,
  }) => listTasks(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listTasks>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListTasksQueryResult = NonNullable<
  Awaited<ReturnType<typeof listTasks>>
>;
export type ListTasksQueryError = ErrorType<unknown>;

/**
 * @summary List tasks
 */

export function useListTasks<
  TData = Awaited<ReturnType<typeof listTasks>>,
  TError = ErrorType<unknown>,
>(
  params?: ListTasksParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listTasks>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListTasksQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a task
 */
export const getCreateTaskUrl = () => {
  return `/api/tasks`;
};

export const createTask = async (
  createTaskBody: CreateTaskBody,
  options?: RequestInit,
): Promise<Task> => {
  return customFetch<Task>(getCreateTaskUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createTaskBody),
  });
};

export const getCreateTaskMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTask>>,
    TError,
    { data: BodyType<CreateTaskBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTask>>,
  TError,
  { data: BodyType<CreateTaskBody> },
  TContext
> => {
  const mutationKey = ["createTask"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTask>>,
    { data: BodyType<CreateTaskBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createTask(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTaskMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTask>>
>;
export type CreateTaskMutationBody = BodyType<CreateTaskBody>;
export type CreateTaskMutationError = ErrorType<unknown>;

/**
 * @summary Create a task
 */
export const useCreateTask = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTask>>,
    TError,
    { data: BodyType<CreateTaskBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createTask>>,
  TError,
  { data: BodyType<CreateTaskBody> },
  TContext
> => {
  return useMutation(getCreateTaskMutationOptions(options));
};

export const getUpdateTaskUrl = (id: number) => {
  return `/api/tasks/${id}`;
};

export const updateTask = async (
  id: number,
  updateTaskBody: UpdateTaskBody,
  options?: RequestInit,
): Promise<Task> => {
  return customFetch<Task>(getUpdateTaskUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateTaskBody),
  });
};

export const getUpdateTaskMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTask>>,
    TError,
    { id: number; data: BodyType<UpdateTaskBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTask>>,
  TError,
  { id: number; data: BodyType<UpdateTaskBody> },
  TContext
> => {
  const mutationKey = ["updateTask"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTask>>,
    { id: number; data: BodyType<UpdateTaskBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateTask(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTaskMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateTask>>
>;
export type UpdateTaskMutationBody = BodyType<UpdateTaskBody>;
export type UpdateTaskMutationError = ErrorType<unknown>;

export const useUpdateTask = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTask>>,
    TError,
    { id: number; data: BodyType<UpdateTaskBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateTask>>,
  TError,
  { id: number; data: BodyType<UpdateTaskBody> },
  TContext
> => {
  return useMutation(getUpdateTaskMutationOptions(options));
};

export const getDeleteTaskUrl = (id: number) => {
  return `/api/tasks/${id}`;
};

export const deleteTask = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteTaskUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteTaskMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTask>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteTask>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteTask"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteTask>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteTask(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteTaskMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteTask>>
>;

export type DeleteTaskMutationError = ErrorType<unknown>;

export const useDeleteTask = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteTask>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteTask>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteTaskMutationOptions(options));
};

/**
 * @summary List meal plans
 */
export const getListMealsUrl = (params?: ListMealsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/meals?${stringifiedParams}`
    : `/api/meals`;
};

export const listMeals = async (
  params?: ListMealsParams,
  options?: RequestInit,
): Promise<Meal[]> => {
  return customFetch<Meal[]>(getListMealsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getListMealsQueryKey = (params?: ListMealsParams) => {
  return [`/api/meals`, ...(params ? [params] : [])] as const;
};

export const getListMealsQueryOptions = <
  TData = Awaited<ReturnType<typeof listMeals>>,
  TError = ErrorType<unknown>,
>(
  params?: ListMealsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listMeals>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListMealsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listMeals>>> = ({
    signal,
  }) => listMeals(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listMeals>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListMealsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listMeals>>
>;
export type ListMealsQueryError = ErrorType<unknown>;

/**
 * @summary List meal plans
 */

export function useListMeals<
  TData = Awaited<ReturnType<typeof listMeals>>,
  TError = ErrorType<unknown>,
>(
  params?: ListMealsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listMeals>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListMealsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a meal plan entry
 */
export const getCreateMealUrl = () => {
  return `/api/meals`;
};

export const createMeal = async (
  createMealBody: CreateMealBody,
  options?: RequestInit,
): Promise<Meal> => {
  return customFetch<Meal>(getCreateMealUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createMealBody),
  });
};

export const getCreateMealMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMeal>>,
    TError,
    { data: BodyType<CreateMealBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createMeal>>,
  TError,
  { data: BodyType<CreateMealBody> },
  TContext
> => {
  const mutationKey = ["createMeal"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createMeal>>,
    { data: BodyType<CreateMealBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createMeal(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateMealMutationResult = NonNullable<
  Awaited<ReturnType<typeof createMeal>>
>;
export type CreateMealMutationBody = BodyType<CreateMealBody>;
export type CreateMealMutationError = ErrorType<unknown>;

/**
 * @summary Create a meal plan entry
 */
export const useCreateMeal = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createMeal>>,
    TError,
    { data: BodyType<CreateMealBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createMeal>>,
  TError,
  { data: BodyType<CreateMealBody> },
  TContext
> => {
  return useMutation(getCreateMealMutationOptions(options));
};

export const getUpdateMealUrl = (id: number) => {
  return `/api/meals/${id}`;
};

export const updateMeal = async (
  id: number,
  createMealBody: CreateMealBody,
  options?: RequestInit,
): Promise<Meal> => {
  return customFetch<Meal>(getUpdateMealUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createMealBody),
  });
};

export const getUpdateMealMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMeal>>,
    TError,
    { id: number; data: BodyType<CreateMealBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateMeal>>,
  TError,
  { id: number; data: BodyType<CreateMealBody> },
  TContext
> => {
  const mutationKey = ["updateMeal"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateMeal>>,
    { id: number; data: BodyType<CreateMealBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateMeal(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateMealMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateMeal>>
>;
export type UpdateMealMutationBody = BodyType<CreateMealBody>;
export type UpdateMealMutationError = ErrorType<unknown>;

export const useUpdateMeal = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateMeal>>,
    TError,
    { id: number; data: BodyType<CreateMealBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateMeal>>,
  TError,
  { id: number; data: BodyType<CreateMealBody> },
  TContext
> => {
  return useMutation(getUpdateMealMutationOptions(options));
};

export const getDeleteMealUrl = (id: number) => {
  return `/api/meals/${id}`;
};

export const deleteMeal = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteMealUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteMealMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMeal>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteMeal>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteMeal"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteMeal>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteMeal(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteMealMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteMeal>>
>;

export type DeleteMealMutationError = ErrorType<unknown>;

export const useDeleteMeal = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteMeal>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteMeal>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteMealMutationOptions(options));
};

/**
 * @summary Get dashboard summary counts and upcoming items
 */
export const getGetDashboardSummaryUrl = () => {
  return `/api/dashboard/summary`;
};

export const getDashboardSummary = async (
  options?: RequestInit,
): Promise<DashboardSummary> => {
  return customFetch<DashboardSummary>(getGetDashboardSummaryUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetDashboardSummaryQueryKey = () => {
  return [`/api/dashboard/summary`] as const;
};

export const getGetDashboardSummaryQueryOptions = <
  TData = Awaited<ReturnType<typeof getDashboardSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDashboardSummaryQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getDashboardSummary>>
  > = ({ signal }) => getDashboardSummary({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardSummary>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetDashboardSummaryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDashboardSummary>>
>;
export type GetDashboardSummaryQueryError = ErrorType<unknown>;

/**
 * @summary Get dashboard summary counts and upcoming items
 */

export function useGetDashboardSummary<
  TData = Awaited<ReturnType<typeof getDashboardSummary>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getDashboardSummary>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetDashboardSummaryQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get next 7 days of events
 */
export const getGetUpcomingEventsUrl = () => {
  return `/api/dashboard/upcoming-events`;
};

export const getUpcomingEvents = async (
  options?: RequestInit,
): Promise<CalendarEvent[]> => {
  return customFetch<CalendarEvent[]>(getGetUpcomingEventsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetUpcomingEventsQueryKey = () => {
  return [`/api/dashboard/upcoming-events`] as const;
};

export const getGetUpcomingEventsQueryOptions = <
  TData = Awaited<ReturnType<typeof getUpcomingEvents>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getUpcomingEvents>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUpcomingEventsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getUpcomingEvents>>
  > = ({ signal }) => getUpcomingEvents({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getUpcomingEvents>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetUpcomingEventsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUpcomingEvents>>
>;
export type GetUpcomingEventsQueryError = ErrorType<unknown>;

/**
 * @summary Get next 7 days of events
 */

export function useGetUpcomingEvents<
  TData = Awaited<ReturnType<typeof getUpcomingEvents>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getUpcomingEvents>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetUpcomingEventsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get all incomplete tasks
 */
export const getGetPendingTasksUrl = () => {
  return `/api/dashboard/pending-tasks`;
};

export const getPendingTasks = async (
  options?: RequestInit,
): Promise<Task[]> => {
  return customFetch<Task[]>(getGetPendingTasksUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetPendingTasksQueryKey = () => {
  return [`/api/dashboard/pending-tasks`] as const;
};

export const getGetPendingTasksQueryOptions = <
  TData = Awaited<ReturnType<typeof getPendingTasks>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPendingTasks>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPendingTasksQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPendingTasks>>> = ({
    signal,
  }) => getPendingTasks({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPendingTasks>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetPendingTasksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPendingTasks>>
>;
export type GetPendingTasksQueryError = ErrorType<unknown>;

/**
 * @summary Get all incomplete tasks
 */

export function useGetPendingTasks<
  TData = Awaited<ReturnType<typeof getPendingTasks>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getPendingTasks>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetPendingTasksQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get this week's meal plan
 */
export const getGetThisWeekMealsUrl = () => {
  return `/api/dashboard/this-week-meals`;
};

export const getThisWeekMeals = async (
  options?: RequestInit,
): Promise<Meal[]> => {
  return customFetch<Meal[]>(getGetThisWeekMealsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetThisWeekMealsQueryKey = () => {
  return [`/api/dashboard/this-week-meals`] as const;
};

export const getGetThisWeekMealsQueryOptions = <
  TData = Awaited<ReturnType<typeof getThisWeekMeals>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getThisWeekMeals>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetThisWeekMealsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getThisWeekMeals>>
  > = ({ signal }) => getThisWeekMeals({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getThisWeekMeals>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetThisWeekMealsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getThisWeekMeals>>
>;
export type GetThisWeekMealsQueryError = ErrorType<unknown>;

/**
 * @summary Get this week's meal plan
 */

export function useGetThisWeekMeals<
  TData = Awaited<ReturnType<typeof getThisWeekMeals>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getThisWeekMeals>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetThisWeekMealsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List AI conversations
 */
export const getListOpenaiConversationsUrl = () => {
  return `/api/openai/conversations`;
};

export const listOpenaiConversations = async (
  options?: RequestInit,
): Promise<Conversation[]> => {
  return customFetch<Conversation[]>(getListOpenaiConversationsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListOpenaiConversationsQueryKey = () => {
  return [`/api/openai/conversations`] as const;
};

export const getListOpenaiConversationsQueryOptions = <
  TData = Awaited<ReturnType<typeof listOpenaiConversations>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiConversations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListOpenaiConversationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listOpenaiConversations>>
  > = ({ signal }) => listOpenaiConversations({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiConversations>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListOpenaiConversationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listOpenaiConversations>>
>;
export type ListOpenaiConversationsQueryError = ErrorType<unknown>;

/**
 * @summary List AI conversations
 */

export function useListOpenaiConversations<
  TData = Awaited<ReturnType<typeof listOpenaiConversations>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiConversations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListOpenaiConversationsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new AI conversation
 */
export const getCreateOpenaiConversationUrl = () => {
  return `/api/openai/conversations`;
};

export const createOpenaiConversation = async (
  createConversationBody: CreateConversationBody,
  options?: RequestInit,
): Promise<Conversation> => {
  return customFetch<Conversation>(getCreateOpenaiConversationUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createConversationBody),
  });
};

export const getCreateOpenaiConversationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOpenaiConversation>>,
    TError,
    { data: BodyType<CreateConversationBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOpenaiConversation>>,
  TError,
  { data: BodyType<CreateConversationBody> },
  TContext
> => {
  const mutationKey = ["createOpenaiConversation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOpenaiConversation>>,
    { data: BodyType<CreateConversationBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createOpenaiConversation(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOpenaiConversationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOpenaiConversation>>
>;
export type CreateOpenaiConversationMutationBody =
  BodyType<CreateConversationBody>;
export type CreateOpenaiConversationMutationError = ErrorType<unknown>;

/**
 * @summary Create a new AI conversation
 */
export const useCreateOpenaiConversation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOpenaiConversation>>,
    TError,
    { data: BodyType<CreateConversationBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createOpenaiConversation>>,
  TError,
  { data: BodyType<CreateConversationBody> },
  TContext
> => {
  return useMutation(getCreateOpenaiConversationMutationOptions(options));
};

export const getListOpenaiConversationMessagesUrl = (id: number) => {
  return `/api/openai/conversations/${id}/messages`;
};

export const listOpenaiConversationMessages = async (
  id: number,
  options?: RequestInit,
): Promise<Message[]> => {
  return customFetch<Message[]>(getListOpenaiConversationMessagesUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getListOpenaiConversationMessagesQueryKey = (id: number) => {
  return [`/api/openai/conversations/${id}/messages`] as const;
};

export const getListOpenaiConversationMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof listOpenaiConversationMessages>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listOpenaiConversationMessages>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListOpenaiConversationMessagesQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listOpenaiConversationMessages>>
  > = ({ signal }) =>
    listOpenaiConversationMessages(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiConversationMessages>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListOpenaiConversationMessagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listOpenaiConversationMessages>>
>;
export type ListOpenaiConversationMessagesQueryError = ErrorType<unknown>;

export function useListOpenaiConversationMessages<
  TData = Awaited<ReturnType<typeof listOpenaiConversationMessages>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listOpenaiConversationMessages>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListOpenaiConversationMessagesQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getSendOpenaiMessageUrl = (id: number) => {
  return `/api/openai/conversations/${id}/messages`;
};

export const sendOpenaiMessage = async (
  id: number,
  sendOpenaiMessageBody: SendOpenaiMessageBody,
  options?: RequestInit,
): Promise<string> => {
  return customFetch<string>(getSendOpenaiMessageUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(sendOpenaiMessageBody),
  });
};

export const getSendOpenaiMessageMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendOpenaiMessage>>,
    TError,
    { id: number; data: BodyType<SendOpenaiMessageBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendOpenaiMessage>>,
  TError,
  { id: number; data: BodyType<SendOpenaiMessageBody> },
  TContext
> => {
  const mutationKey = ["sendOpenaiMessage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendOpenaiMessage>>,
    { id: number; data: BodyType<SendOpenaiMessageBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return sendOpenaiMessage(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendOpenaiMessageMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendOpenaiMessage>>
>;
export type SendOpenaiMessageMutationBody = BodyType<SendOpenaiMessageBody>;
export type SendOpenaiMessageMutationError = ErrorType<unknown>;

export const useSendOpenaiMessage = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendOpenaiMessage>>,
    TError,
    { id: number; data: BodyType<SendOpenaiMessageBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendOpenaiMessage>>,
  TError,
  { id: number; data: BodyType<SendOpenaiMessageBody> },
  TContext
> => {
  return useMutation(getSendOpenaiMessageMutationOptions(options));
};
